{
  try {
    return run(query);
  }
 catch (  final Exception ex) {
    final AssertionError err=new AssertionError("Query failed:\n" + query);
    err.initCause(ex);
    throw err;
  }
}
