{
  try {
    return run(query);
  }
 catch (  final Exception ex) {
    Util.errln(Util.message(ex));
    Util.stack(12);
    final AssertionError err=new AssertionError("Query failed:\n" + query);
    err.initCause(ex);
    throw err;
  }
}
