{
  try {
    return eval(query);
  }
 catch (  final QueryException|IOException ex) {
    Util.stack(ex);
    final AssertionError err=new AssertionError("Query failed:\n" + query);
    err.initCause(ex);
    throw err;
  }
}
