{
  try {
    XQException ex=new XQException("Hello world!","VendorCode");
    assertNull("A-XQEX-3.1: getNextException returns null when last in chain",ex.getNextException());
  }
 catch (  Exception e) {
    fail("A-XQEX-3.1: getNextException failed with message: " + e.getMessage());
  }
  try {
    XQException ex1=new XQException("Hello world!","VendorCode");
    XQException ex2=new XQException("Hello world!","VendorCode");
    ex1.setNextException(ex2);
    assertEquals("A-XQEX-3.2: getNextException returns next exception",ex2,ex1.getNextException());
  }
 catch (  Exception e) {
    fail("A-XQEX-3.2: getNextException failed with message: " + e.getMessage());
  }
}
