{
  try {
    XQQueryException ex=new XQQueryException("Hello world!","VendorCode",new QName("foo"),7,8,56);
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created","Hello world!",ex.getMessage());
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created","VendorCode",ex.getVendorCode());
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created",new QName("foo"),ex.getErrorCode());
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created",7,ex.getLineNumber());
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created",8,ex.getColumnNumber());
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created",56,ex.getPosition());
  }
 catch (  Exception e) {
    junit.framework.Assert.fail("A-XQQEX-1.1: Creating XQQueryException faild with message: " + e.getMessage());
  }
}
