{
  try {
    final XQException ex1=new XQException("Hello world!","VendorCode");
    final XQException ex2=new XQException("Hello world!","VendorCode");
    ex1.setNextException(ex2);
    assertEquals("A-XQEX-4.1: setNextException sets the next exception in the chain",ex2,ex1.getNextException());
  }
 catch (  final Exception e) {
    fail("A-XQEX-4.1 : setNextException failed with message: " + e.getMessage());
  }
}
