{
  try {
    return method.invoke(object,args);
  }
 catch (  final Exception ex) {
    Util.debug(ex);
    return null;
  }
}
