{
  try {
    XQException ex1=new XQException("Hello world!","VendorCode");
    XQException ex2=new XQException("Hello world!","VendorCode");
    ex1.setNextException(ex2);
    junit.framework.Assert.assertEquals("A-XQEX-4.1: setNextException sets the next exception in the chain",ex2,ex1.getNextException());
  }
 catch (  Exception e) {
    junit.framework.Assert.fail("A-XQEX-4.1 : setNextException failed with message: " + e.getMessage());
  }
}
